// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250813012507_addProductIndb")]
    partial class addProductIndb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Actions"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "History"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "SciFi"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Amr ELdeeb",
                            Description = "No Now Pro",
                            ISBN = "7332",
                            ListPrice = 80.0,
                            Price = 75.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            Title = "Coffee Machine"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sara Khaled",
                            Description = "Fast boil 1.7L",
                            ISBN = "4821",
                            ListPrice = 50.0,
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Electric Kettle"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mohamed Ali",
                            Description = "600W with glass jar",
                            ISBN = "9154",
                            ListPrice = 120.0,
                            Price = 110.0,
                            Price100 = 90.0,
                            Price50 = 100.0,
                            Title = "Blender"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Omar Fathy",
                            Description = "20L compact microwave",
                            ISBN = "6723",
                            ListPrice = 200.0,
                            Price = 190.0,
                            Price100 = 170.0,
                            Price50 = 180.0,
                            Title = "Microwave Oven"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Nour Hassan",
                            Description = "3.5L oil-free cooking",
                            ISBN = "8439",
                            ListPrice = 150.0,
                            Price = 140.0,
                            Price100 = 120.0,
                            Price50 = 130.0,
                            Title = "Air Fryer"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Amr ELdeeb",
                            Description = "15 bar pump pressure",
                            ISBN = "2948",
                            ListPrice = 250.0,
                            Price = 240.0,
                            Price100 = 220.0,
                            Price50 = 230.0,
                            Title = "Espresso Machine"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ali Ahmed",
                            Description = "2-slice stainless steel",
                            ISBN = "3572",
                            ListPrice = 40.0,
                            Price = 38.0,
                            Price100 = 32.0,
                            Price50 = 35.0,
                            Title = "Toaster"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Huda Samir",
                            Description = "1.8L automatic keep warm",
                            ISBN = "7810",
                            ListPrice = 90.0,
                            Price = 85.0,
                            Price100 = 75.0,
                            Price50 = 80.0,
                            Title = "Rice Cooker"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Khaled Mansour",
                            Description = "5L bowl, 6-speed settings",
                            ISBN = "5264",
                            ListPrice = 300.0,
                            Price = 290.0,
                            Price100 = 270.0,
                            Price50 = 280.0,
                            Title = "Stand Mixer"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Aya Adel",
                            Description = "Variable speed control",
                            ISBN = "6491",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Hand Blender"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
