// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250813042123_addsedingdatOfproduct")]
    partial class addsedingdatOfproduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 0,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 0,
                            Name = "Furniture"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Coffee Experts Co.",
                            CategoryId = 1,
                            Description = "Specialized machine for cold brew coffee",
                            ISBN = "CM-1011",
                            ListPrice = 150.0,
                            Price = 140.0,
                            Price100 = 120.0,
                            Price50 = 130.0,
                            Title = "Cold Brew Coffee Maker"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Coffee Experts Co.",
                            CategoryId = 2,
                            Description = "Classic French press with stainless steel plunger",
                            ISBN = "CM-1012",
                            ListPrice = 80.0,
                            Price = 75.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            Title = "French Press Coffee Set"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Coffee Experts Co.",
                            CategoryId = 3,
                            Description = "Coffee machine with built-in smart grinder",
                            ISBN = "CM-1013",
                            ListPrice = 500.0,
                            Price = 480.0,
                            Price100 = 440.0,
                            Price50 = 460.0,
                            Title = "Smart Grinder Coffee Machine"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Coffee Experts Co.",
                            CategoryId = 1,
                            Description = "Handheld espresso machine for coffee on the go",
                            ISBN = "CM-1014",
                            ListPrice = 90.0,
                            Price = 85.0,
                            Price100 = 75.0,
                            Price50 = 80.0,
                            Title = "Portable Espresso Maker"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Coffee Experts Co.",
                            CategoryId = 2,
                            Description = "Machine designed for barista practice and training",
                            ISBN = "CM-1015",
                            ListPrice = 650.0,
                            Price = 620.0,
                            Price100 = 580.0,
                            Price50 = 600.0,
                            Title = "Barista Training Coffee Machine"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
